### ISSUE TITLE
Support batch writing of values？

### ISSUE THREAD

**Issue by Ri0nGo** [danomagnum/gologix#10]
Hi，Does it support batch writing of values? Only a single write value is seen in the example directory

**Comment by danomagnum** [comment]
Yes.  It supports writing multiple values at once with `gologix:"<tagname>"` tagged structs.  It also has the ability to do a map[string]interface{} with the writeDict() function where the keys of the map are the tag paths and the values are the values to write, but this isn't exported for some reason.

I'll try and get that exported for easier use (read already has this exported as the ReadList() function) and get an example made up for it.

In the meantime you should be able to use a tagged struct like I said.

**Comment by danomagnum** [comment]
I released beta 17 where I have made the function for writing multiple tags at once external.  See "MultiWrite" in the example folder for what I think you're looking for.

Let me know if you have any issues.

**Comment by Ri0nGo** [comment]
That is my want. Thank you.
