### ISSUE TITLE
read or write SINT8 to get a error 

### ISSUE THREAD

**Issue by Ri0nGo** [danomagnum/gologix#24]
1. When using readValue to read a value of type sint, the code uses byte to parse the value, but byte is essentially uint8, so the parsed data type is uint8, the correct way to parse the data is to use int8.

```go
func readValue(t CIPType, r io.Reader) (any, error) {
	var value any
	var err error
	switch t {
	......
	case CIPTypeSINT:
                // var trueval int8
		var trueval byte   // can't use byte
		err = binary.Read(r, binary.LittleEndian, &trueval)
		value = trueval
``` 

Feel free to point out if I've misunderstood.

2. When writing the value, I found that I can't write sint and usint, the code doesn't implement these two cases, usint uses byte as the case, but the value of byte's caseCIPType is not the same as the value of USINTCIPType, it's convenient to ask what was the reason that these two types were not implemented at that time to write the value

```go
// types.go
func GoVarToCIPType(T any) (CIPType, int) {
	switch x := T.(type) {
	case bool:
		return CIPTypeBOOL, 1
	case byte:   // byte ciptype not equal to usint ciptype value
		return CIPTypeBYTE, 1
	case uint16:
		return CIPTypeUINT, 1
	case int16:
		return CIPTypeINT, 1
```

Your warehouse has been a great help to me.
Thank you very much, looking forward to your reply

**Comment by danomagnum** [comment]
Those are good points.  I will take a look at it this evening, but nothing comes to mind as to why these fixes wouldn't work.

**Comment by danomagnum** [comment]
Beta 26 now uses int8 as the correct type for SINT on the controllers.  Give it a try and let me know if it works.

I don't have one of the newer L8 controllers so I can't test against USINTs, but SINTs should work now.

**Comment by Ri0nGo** [comment]
Thanks a lot, sint8 is working, I simulated a server using python as a test reference.

```python
import sys
from cpppo.server.enip.main import main as enip_main

def main( **kwds ):
    args_list = ['--print', '-v']
    args_list.append('TAG1=REAL')
    args_list.append('TAG2=BOOL')
    args_list.append('TAG3=DINT')
    args_list.append('TAG4=LINT')
    args_list.append('TAG5=INT')
    args_list.append('TAG6=SINT')
    args_list.append('TAG7=USINT')
    args_list.append('TAG8=UINT')
    args_list.append('TAG9=UDINT')
    args_list.append('TAG10=LREAL')

    # Establish Identity and TCPIP objects w/ some custom data for the test, from a config file
    return enip_main(args_list)

if __name__ == "__main__":
    sys.exit( main() )

```

**Comment by Ri0nGo** [comment]
solve the problem
